export { default as About } from './About'
export { default as CallToAction } from './CallToAction'
export { default as Contacts } from './Contacts'
export { default as Features } from './Features'
export { default as Hero } from './Hero'
export { default as Reviews } from './Reviews'