export const SERVICE_METADATA_KEYS = {
  serviceSlug: "repair:service_slug",
  serviceName: "repair:service_name",
  serviceGroup: "repair:service_group",
  serviceCategory: "repair:service_category",
  requestedAt: "repair:requested_at",
  customerFullName: "repair:customer_full_name",
  customerPhone: "repair:customer_phone",
  customerEmail: "repair:customer_email",
  customerMessage: "repair:customer_message",
  preferredContact: "repair:preferred_contact",
  deviceType: "repair:device_type",
  urgent: "repair:is_urgent",
  needsPickup: "repair:needs_pickup",
  consent: "repair:consent",
  calculatorModifiers: "repair:calculator_modifiers",
  estimateCurrency: "repair:estimate_currency",
  estimateMin: "repair:estimate_min",
  estimateMax: "repair:estimate_max",
  workerId: "repair:worker_id",
  workerEmail: "repair:worker_email",
  workerName: "repair:worker_name",
  workerGroup: "repair:worker_group",
  leadGroup: "repair:lead_group",
  leadPriorityUntil: "repair:lead_priority_until",
  stage: "repair:stage",
  stageUpdatedAt: "repair:stage_updated_at",
};

export const DELIVERY_METADATA_KEYS = {
  stage: "delivery:stage",
  stageUpdatedAt: "delivery:stage_updated_at",
  courierId: "delivery:courier_id",
  courierEmail: "delivery:courier_email",
  courierName: "delivery:courier_name",
  courierGroup: "delivery:courier_group",
};
